title: Explicitly Connected Layout & Depth
description: Monocular Spherical Depth Estimation with Explicitly Connected Weak Layout Cues
show_downloads: false
theme: jekyll-theme-architect

github:
  data_url: https://vcl3d.github.io/Pano3D
  # models_url: 
  owner_url: https://zokin.github.io
  owner_name: Nikolaos Zioulis
  
google_analytics: UA-147231916-1
